import { Recursive } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const recursive = Recursive({
	subsets: ["latin"],
	weight: ["300", "400", "500", "600", "700", "800", "900", "1000"],
});

export const metadata = {
	title: "Filerial",
	description: "Generated by danarwijanarko",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${recursive.className} bg-[#0f1014] ps-24`}
				suppressHydrationWarning={true}
			>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
