import { Recursive } from "next/font/google";
import "./globals.css";

const recursive = Recursive({ subsets: ["latin"] });

export const metadata = {
  title: "Filerial",
  description: "Generated by danarwijanarko",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={recursive.className}>{children}</body>
    </html>
  );
}
